title: DH340 - AI & Digital Humanities
description: Exploring AI through Digital Humanities - A course at Michigan State University
theme_color: "#18453B"
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
url: "https://koutiany.github.io"
baseurl: "/dh340ss26ai"
